name: 'Delete old artifacts and clean docker'
on:
  schedule:
    - cron: '* 12 10-16/2 * *' # every hour

jobs:
  clean-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run docker cleaner
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock zzrot/docker-clean run
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0days # Setting this to 0 will delete all artifacts
