name: Cloud docker-compose Stack
on:
  pull_request:
    branches:
      - main
jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate .env file
        run: cp docker/cloud/.env.example docker/cloud/.env
      - name: Build the stack
        run: docker-compose up -d
      # - name: Test # TODO add tests: filebrowser, syncthing, mapeo-icons, fdroid-repo
